# This workflow will deploy source code on Cloud Run when a commit is pushed to the "main" branch
#
# Overview:
#
# 1. Authenticate to Google Cloud
# 2. Deploy it to Cloud Run
#
# To configure this workflow:
#
# 1. Ensure the required Google Cloud APIs are enabled:
#
#    Cloud Run            run.googleapis.com
#    Cloud Build          cloudbuild.googleapis.com
#    Artifact Registry    artifactregistry.googleapis.com
#
# 2. Create and configure Workload Identity Federation for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 3. Ensure the required IAM permissions are granted
#
#    Cloud Run
#      roles/run.admin
#      roles/iam.serviceAccountUser     (to act as the Cloud Run runtime service account)
#
#    Cloud Build
#      roles/cloudbuild.builds.editor
#
#    Cloud Storage
#      roles/storage.objectAdmin
#
#    Artifact Registry
#      roles/artifactregistry.admin     (project or repository level)
#
#    NOTE: You should always follow the principle of least privilege when assigning IAM roles
#
# 4. Create GitHub secrets for WIF_PROVIDER and WIF_SERVICE_ACCOUNT
#
# 5. Change the values for the SERVICE and REGION environment variables (below).
#
# For more support on how to run this workflow, please visit https://github.com/marketplace/actions/deploy-to-cloud-run
#
# Further reading:
#   Cloud Run runtime service account   - https://cloud.google.com/run/docs/securing/service-identity
#   Cloud Run IAM permissions           - https://cloud.google.com/run/docs/deploying-source-code#permissions_required_to_deploy
#   Cloud Run builds from source        - https://cloud.google.com/run/docs/deploying-source-code
#   Principle of least privilege        - https://cloud.google.com/blog/products/identity-security/dont-get-pwned-practicing-the-principle-of-least-privilege

name: vrcg_pipeline

on:

  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
    - "vrcg_pipeline**"

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.VRCG_SECRET }}

      - name: SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'


          
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with: 
          name: vrcg_pipeline
          runtime: python38
          project_id: vrcg-database
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/vrcg-database/topics/vrcg-pipeline-trigger
          source_dir: ./vrcg_pipeline/
          timeout: 540
          memory_mb: 1024
        
        
#        run: |
#          gcloud builds submit --pack image=gcr.io/vrcg-database/vrcg_pipeline:$GITHUB_SHA ./vrcg_pipeline
#          gcloud run deploy vrcg_pipeline \
#           --image gcr.io/vrcg-database/vrcg_pipeline:$GITHUB_SHA \
#            --platform managed \
#            --region us-central1 \
#            --timeout 540 \
#            --memory 1024Mi \
#            --update-labels managed-by=github-actions,commit-sha=$GITHUB_SHA \
#            --project vrcg-database
