name: vrcg_pipeline

on:

  workflow_dispatch:

  push:
    branches: [ "main" ]
    paths:
    - "vrcg_pipeline**"

jobs:

  build:
  
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.VRCG_SECRET }}

      - name: SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'
          
      - name: Deploy
        uses: google-github-actions/deploy-cloud-functions@v1
        with: 
          name: vrcg_pipeline
          runtime: python38
          entry_point: main
          project_id: vrcg-database
          image: us-docker.pkg.dev/vrcg-database/vrcg-pipeline
          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
          event_trigger_resource: projects/vrcg-database/topics/vrcg-pipeline-trigger
          source_dir: ./vrcg_pipeline/
          timeout: 540
          memory_mb: 1024
        
        
#        run: |
#          gcloud builds submit --pack image=gcr.io/vrcg-database/vrcg_pipeline:$GITHUB_SHA ./vrcg_pipeline
#          gcloud run deploy vrcg_pipeline \
#           --image gcr.io/vrcg-database/vrcg_pipeline:$GITHUB_SHA \
#            --platform managed \
#            --region us-central1 \
#            --timeout 540 \
#            --memory 1024Mi \
#            --update-labels managed-by=github-actions,commit-sha=$GITHUB_SHA \
#            --project vrcg-database
