name: vrcg_pipeline
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - "vrcg_pipeline**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.VRCG_SECRET }}

      - name: SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Build and Push Container
        run: |
          gcloud builds submit --tag gcr.io/vrcg-database/vrcg_pipeline:${{ github.sha }} .

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy vrcg_pipeline \
            --image gcr.io/vrcg-database/vrcg_pipeline:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars=UN=${{ secrets.UN }},PW=${{ secrets.PW }},IM=${{ secrets.IM }},SMTP=${{ secrets.SMTP }}

#      - name: Deploy to Cloud Run
#        uses: google-github-actions/deploy-cloudrun@v1
#        with:
#          service: vrcg_pipeline
#          image: gcr.io/vrcg-database/vrcg_pipeline
#          region: us-central1
#          project_id: vrcg-database
#          timeout: 540s
