name: vrcg_pipeline
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - "vrcg_pipeline**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.VRCG_SECRET }}

      - name: SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Build and Push Container
        run: |
          echo "Current directory structure:"
          tree -L 2
          echo "Contents of vrcg_pipeline directory:"
          ls -la vrcg_pipeline
          echo "Contents of Dockerfile:"
          cat vrcg_pipeline/Dockerfile
          echo "Starting build..."
          gcloud builds submit vrcg_pipeline --tag us-docker.pkg.dev/vrcg-database/vrcg-pipeline/vrcg_pipeline:${{ github.sha }}
          echo "Build completed. Verifying image..."
          gcloud artifacts docker images list us-docker.pkg.dev/vrcg-database/vrcg-pipeline

      - name: Deploy to Cloud Run
        run: |
          echo "Deploying image us-docker.pkg.dev/vrcg-database/vrcg-pipeline/vrcg_pipeline:${{ github.sha }}"
          gcloud run deploy vrcg_pipeline \
            --image us-docker.pkg.dev/vrcg-database/vrcg-pipeline/vrcg_pipeline:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars=UN=${{ secrets.UN }},PW=${{ secrets.PW }},IM=${{ secrets.IM }},SMTP=${{ secrets.SMTP }}
