name: vrcg_pipeline
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - "vrcg_pipeline**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Auth
        id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.VRCG_SECRET }}

      - name: SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      - name: Build and Push Container
        run: |
          gcloud builds submit --tag gcr.io/vrcg-database/vrcg_pipeline .

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: vrcg_pipeline
          image: gcr.io/vrcg-database/vrcg_pipeline
          region: us-central1
          project_id: vrcg-database
          timeout: 540s

          
#      - name: Deploy
#        uses: google-github-actions/deploy-cloud-functions@v1
#        with: 
#          name: vrcg_pipeline
#          runtime: python38
#          entry_point: main
#          project_id: vrcg-database
#          image: gcr.io/vrcg-database/vrcg-pipeline
#          event_trigger_type: providers/cloud.pubsub/eventTypes/topic.publish
#          event_trigger_resource: projects/vrcg-database/topics/vrcg-pipeline-trigger
#          source_dir: ./vrcg_pipeline/
#          timeout: 540
#          memory_mb: 1024
